title: Sricharan Vijayarangan
description: Eclectic Autodidact 
site_title: '@acrarshin - Sricharan Vijayarangan'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: acrarshin 
blog_url: https://compactml.wordpress.com/
email: sricharan2010@gmail.com 
keybase_username: acrarshin 
twitter_username: acrarshin 
reddit_username: acrarshin 

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 
